feat: add tamagui
can't seem to solve
SyntaxError: Unexpected token 'typeof'
at compileSourceTextModule (node:internal/modules/esm/utils:346:16)
at ModuleLoader.importSyncForRequire
(node:internal/modules/esm/loader:382:18)
at loadESMFromCJS (node:internal/modules/cjs/loader:1363:24)
at Module._compile (node:internal/modules/cjs/loader:1503:5)
at Object..js (node:internal/modules/cjs/loader:1623:10)
at Module.load (node:internal/modules/cjs/loader:1266:32)
at Function._load (node:internal/modules/cjs/loader:1091:12)
at Module.require (node:internal/modules/cjs/loader:1289:19)
at require (node:internal/modules/helpers:182:18)
at Object.<anonymous>
(/home/oliver/Documents/Developer/web/javascript/tamagui-tanstack-start/node_modules/.pnpm/react-native-svg@15.15.1_react-native@0.83.1_@babel+core@7.28.6_@types+react@19.2.9_react@19.2.3__react@19.2.3/node_modules/react-native-svg/lib/commonjs/lib/SvgTouchableMixin.js:7:20)